<a href="https://colab.research.google.com/github/IvRodco/EstadisticaAplicasa_1899843/blob/main/Sesion8_G41_24ago.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Estadistica Aplicada

##Sesion 8, 24 de agosto

###Ivanna Lizeth Rodriguez Ambriz

###1899843

Grupo 41

In [1]:
#importamos librerias
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

%matplotlib inline

#libreria MCO
import statsmodels.formula.api as smf

In [4]:
from pandas._libs.tslibs.offsets import DateOffset
datos= pd.read_excel('modelolineal.xlsx')
datos=datos[['X','Y']]
datos

     X          Y
0   23  19.246957
1   19  16.878501
2   27  20.187237
3   13  12.176789
4   21  21.420112
5   22  24.436799
6   19  14.507928
7   14  16.013496
8    3  12.043514
9    1   6.808838
10  19  20.473608
11  18  19.688717
12  12  20.405782
13  16  24.959259
14  29  23.913532
15  23  22.719407
16  14  18.680587
17  20  17.192583
18  27  28.422786
19  28  24.757379
20   0   9.544102
21  20  24.230330
22  24  26.417826
23  23  23.066723
24   8  13.145005
25  24  24.385156
26  10  12.934102
27   4  14.002469
28  29  26.599047
29  10  11.910387


estimar $Y= \beta_0+\beta_1 X$

In [9]:
#especificamos el modelo
reg1= smf.ols(formula='Y~X',data= datos)

##estimacion
results1= reg1.fit()

#mostramos
print(results1.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                      Y   R-squared:                       0.732
Model:                            OLS   Adj. R-squared:                  0.722
Method:                 Least Squares   F-statistic:                     76.40
Date:                Thu, 24 Aug 2023   Prob (F-statistic):           1.72e-09
Time:                        20:22:26   Log-Likelihood:                -74.480
No. Observations:                  30   AIC:                             153.0
Df Residuals:                      28   BIC:                             155.8
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      8.9619      1.276      7.022      0.000       6.347      11.576
X              0.5814      0.067      8.740      0.000       0.445       0.718
==============================================================================
Omnibus:                        0.249   Durbin-Watson:                   1.658
Prob(Omnibus):                  0.883   Jarque-Bera (JB):                0.440
Skew:                           0.121   Prob(JB):                        0.803
Kurtosis:                       2.459   Cond. No.                         44.8
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

Para evaluar un modelo generalmente se usa $R^2$ .

Pero no es la unica medida utilizada, tambien se suele usar con bastante precuencia el MAD, MAPE y MSD.



MAD: Desviacion Absoluta Media

MAPE:Error Porcentual Absoluto Medio

MSD: Desviacion Cuadratica Media


$MAD=1/n∑|(Y-\hat(Y))|$

$MAPE=1/n∑|((Y-\hat(Y))/Y)|$

$MAS=1/n∑(Y-\hat(Y))^2$

In [ ]:
## MAD = 1/n * SUMATORIA(|Y-(Y^)|)

estimar el primer modelo

 $Y= \beta_0+\beta_1 X$

In [11]:
#definimos el conjunto de prueba y conjunto de evaluacion
#generamos la X^2

datos['X']=datos['X']**2

#conjunto entrenamiento
train_set= datos[:20]
test_set= datos[20:]

In [12]:
train_set

      X          Y
0   529  19.246957
1   361  16.878501
2   729  20.187237
3   169  12.176789
4   441  21.420112
5   484  24.436799
6   361  14.507928
7   196  16.013496
8     9  12.043514
9     1   6.808838
10  361  20.473608
11  324  19.688717
12  144  20.405782
13  256  24.959259
14  841  23.913532
15  529  22.719407
16  196  18.680587
17  400  17.192583
18  729  28.422786
19  784  24.757379

In [13]:
test_set

      X          Y
20    0   9.544102
21  400  24.230330
22  576  26.417826
23  529  23.066723
24   64  13.145005
25  576  24.385156
26  100  12.934102
27   16  14.002469
28  841  26.599047
29  100  11.910387

In [18]:
#definimos el primer modelo
regm1= smf.ols(formula='Y~X',data= train_set)

#estimamos el modelo
resultsm1= regm1.fit()

In [36]:
#como podemos acceder a los coeficientes

b0m1=resultsm1.params[0]
b1m1=resultsm1.params[1]

In [37]:
#pronostico en un conjunto de evaluacion

test_set['Y_hat']= b0 + (b1 * test_set['X'])

<ipython-input-37-91c060a30529>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_set['Y_hat']= b0 + (b1 * test_set['X'])

In [42]:
#estimar el MAD

MAD1= (test_set['Y']-test_set['Y_hat']).abs().mean()
print(MAD1)

2.338655071670199

In [ ]:
reg2= smf.ols(formula='Y~X+X2',data=train_set)
resultsm2= regm2.fit()

b0m2=resultsm2.params[0]
b1m2=resultsm2.params[1]
b2m2=resultsm2.params[1]

test_set['Y_hat']= b0m2 + (b1m2 * test_set['X'])+ (b2m2*train_set['X2'])
MAD2=(test_set['Y']-test_set['Y_hat']).abs().mean()

print(MAD1,MAD2)

El mejor modelo segun MAD y utilizando validacion cruzada es el primer modelo