<a href="https://colab.research.google.com/github/IvRodco/EstadisticaAplicasa_1899843/blob/main/Sesion4_EA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Estadistica aplicada

###Sesion 4, 14 de agosto

####Ivanna Lizeth Rodriguez Ambriz 1899843

In [ ]:
alumno_dic=['edad']

In [ ]:
dic_keys(['nombre','edad'])

In [ ]:
estadisticaG41.keys()

In [ ]:
estadisticaG41.values()

##Pandas

Se utiliza para manipulas datos estructurados.

Pandas esta construida en base a numpy, eso significa que cualquier funcion de nunpy funciona a en pandas.

En Pandas hay 3 estructuras de datos:
1. Series (unidimencionales)
2. Dataframes (datos en filas y columnas)
3. Panel (se organizan con el tiempo)

Supongamos que conocemos las edades de la siguientes personas:
Juan 10 años, Pedro 20 años, Jorge 30 años, Ale 40 años y Alba 50 años.

In [2]:
Edades=[10,20,30,40,50]

Edades

[10, 20, 30, 40, 50]

In [3]:
import pandas as pd

In [6]:

#vamos a crear la serie con la eiqueta de nombre de cada dato

serie1= pd.Series(Edades,index=['Juan','Pedro','Jorge','Ale','Alba'])
serie1

Juan     10
Pedro    20
Jorge    30
Ale      40
Alba     50
dtype: int64

In [7]:
#calculamos promedio de las edades
serie1.mean()

30.0

In [9]:
#calculamos la varianza
serie1.var()

250.0

In [10]:
#calculamos la desviacion estandar
serie1.std()

15.811388300841896

##Dataframe

los dataframe son datos con filas y columnas

In [13]:
alumno1=['Juan','Perez',23]
alumno2=['Raul','Gonzalez',17]
alumno3=['Jimena','Rosas',20]
alumno4=['Alejandra','Saldaña',21]

#hacemos una lista que contenga a los alumnos
clase_estadistica=[alumno1,alumno2,alumno3,alumno4]
clase_estadistica

[['Juan', 'Perez', 23],
 ['Raul', 'Gonzalez', 17],
 ['Jimena', 'Rosas', 20],
 ['Alejandra', 'Saldaña', 21]]

In [18]:
#creamos el dataframe
df_clase= pd.DataFrame(clase_estadistica,columns=['Nombre','Apellido','Edad'])
type(df_clase)

pandas.core.frame.DataFrame

In [19]:
df_clase

      Nombre  Apellido  Edad
0       Juan     Perez    23
1       Raul  Gonzalez    17
2     Jimena     Rosas    20
3  Alejandra   Saldaña    21

In [20]:
#nos arroja como estasn las filas
df_clase.index

RangeIndex(start=0, stop=4, step=1)

In [48]:
#nos arroja el nombre de las columnas
df_clase.columns

Index(['Nombre', 'Apellido', 'Edad', 'Estado', 'Edad en dias',
       'Edad en meses'],
      dtype='object')

In [26]:
df_clase['Estado']=['Nuevo Leon','Coahuila','Nuevo Leon','Verecruz']
df_clase

      Nombre  Apellido  Edad      Estado
0       Juan     Perez    23  Nuevo Leon
1       Raul  Gonzalez    17    Coahuila
2     Jimena     Rosas    20  Nuevo Leon
3  Alejandra   Saldaña    21    Verecruz

In [72]:

df_clase=df_clase.set_index('Nombre')
df_clase

,Apellido,Edad,Estado,Edad en dias,Edad en meses,Mayor de edad,Condicion de estudio
Nombre,,,,,,,
Juan,Perez,23,Nuevo Leon,8395,276,Es mayor de edad,Egresado
Raul,Gonzalez,17,Coahuila,6205,204,Menor de edad,Prepa
Jimena,Rosas,20,Nuevo Leon,7300,240,Es mayor de edad,Licenciatura
Alejandra,Saldaña,21,Verecruz,7665,252,Es mayor de edad,Licenciatura

In [91]:
df_clase['Edad en dias']=df_clase['Edad']*365
df_clase

,Apellido,Edad,Estado,Edad en dias,Edad en meses,Mayor de edad,Condicion de estudio
Nombre,,,,,,,
Juan,Perez,23,Nuevo Leon,8395,276,Es mayor de edad,Egresado
Raul,Gonzalez,17,Coahuila,6205,204,Menor de edad,Prepa
Jimena,Rosas,20,Nuevo Leon,7300,240,Es mayor de edad,Licenciatura
Alejandra,Saldaña,21,Verecruz,7665,252,Es mayor de edad,Licenciatura

In [92]:
df_clase['Edad en meses']=df_clase['Edad']*12
df_clase

,Apellido,Edad,Estado,Edad en dias,Edad en meses,Mayor de edad,Condicion de estudio
Nombre,,,,,,,
Juan,Perez,23,Nuevo Leon,8395,276,Es mayor de edad,Egresado
Raul,Gonzalez,17,Coahuila,6205,204,Menor de edad,Prepa
Jimena,Rosas,20,Nuevo Leon,7300,240,Es mayor de edad,Licenciatura
Alejandra,Saldaña,21,Verecruz,7665,252,Es mayor de edad,Licenciatura

##Seleccion en Dataframe

1. Seleccion estandar
2. Seleccion de iloc
3. Seleccion loc
4. Seleccion por boleanos (filtros)

In [73]:
# Seleccion estandar

 #seleccionamos solo una columna
 #en este caso seleccionamos apellido
df_clase['Apellido']

Nombre
Juan            Perez
Raul         Gonzalez
Jimena          Rosas
Alejandra     Saldaña
Name: Apellido, dtype: object

In [74]:
 #ahora seleccionamos la columna edad y apellido
df_clase[['Edad','Apellido']]

           Edad  Apellido
Nombre
Juan         23     Perez
Raul         17  Gonzalez
Jimena       20     Rosas
Alejandra    21   Saldaña

In [75]:
#Ahora seelccionamos por filas

#en esta caso seleccionaremos fila de la 0 a la 2
df_clase[0:2]

,Apellido,Edad,Estado,Edad en dias,Edad en meses,Mayor de edad,Condicion de estudio
Nombre,,,,,,,
Juan,Perez,23,Nuevo Leon,8395,276,Es mayor de edad,Egresado
Raul,Gonzalez,17,Coahuila,6205,204,Menor de edad,Prepa

In [76]:
#ahora eligiremos filas y columnas
#Primero de seleccionan las filas y luego las columnas

#En este caso seleccionamos las filas de la 0 a la 2 y la columna edad
df_clase[0:2]['Edad']

Nombre
Juan    23
Raul    17
Name: Edad, dtype: int64

In [77]:
#Ahora seleccionamos las dilas de la 0 a la 2 y la columnas edas y apellido

df_clase[0:2][['Edad','Apellido']]

        Edad  Apellido
Nombre
Juan      23     Perez
Raul      17  Gonzalez

In [78]:
#Seleccion por posicion iloc
#

df_clase.iloc[0:2,1]

Nombre
Juan    23
Raul    17
Name: Edad, dtype: int64

In [79]:
#quiero seleccionar solo la columa, sin fila

df_clase.iloc[:,1]

Nombre
Juan         23
Raul         17
Jimena       20
Alejandra    21
Name: Edad, dtype: int64

In [80]:
#seleccion por etiquetas loc
#dataframe.loc[filas,columnas]

df_clase.loc[:,'Edad']

Nombre
Juan         23
Raul         17
Jimena       20
Alejandra    21
Name: Edad, dtype: int64

In [82]:
df_clase.loc['Juan','Edad']

23

In [83]:
#seleccion de condicionales(boleanos)
df_clase[df_clase['Edad']>20]

,Apellido,Edad,Estado,Edad en dias,Edad en meses,Mayor de edad,Condicion de estudio
Nombre,,,,,,,
Juan,Perez,23,Nuevo Leon,8395,276,Es mayor de edad,Egresado
Alejandra,Saldaña,21,Verecruz,7665,252,Es mayor de edad,Licenciatura

In [60]:
#para el promedio de las edades
df_clase['Edad'].mean()

20.25

In [61]:
#para la desv estandar de las edades
df_clase['Edad'].std()

2.5

In [62]:
#para la suma de las edades
df_clase['Edad'].sum()

81

In [84]:
#funcion si
#np.where(condicion, valor si se cumple,valor si no se cumple)

import numpy as np

df_clase['Mayor de edad']= np.where(df_clase['Edad']>=18,'Es mayor de edad','Menor de edad')
df_clase

,Apellido,Edad,Estado,Edad en dias,Edad en meses,Mayor de edad,Condicion de estudio
Nombre,,,,,,,
Juan,Perez,23,Nuevo Leon,8395,276,Es mayor de edad,Egresado
Raul,Gonzalez,17,Coahuila,6205,204,Menor de edad,Prepa
Jimena,Rosas,20,Nuevo Leon,7300,240,Es mayor de edad,Licenciatura
Alejandra,Saldaña,21,Verecruz,7665,252,Es mayor de edad,Licenciatura

In [85]:
#funcion si conjunto
#np.select(condiciones,valor si se cumple cada condicion,valor si no se cumple una condicion)
condiciones=[df_clase['Edad']<=17,
             df_clase['Edad']<23,
             df_clase['Edad']>=23]
valor_condicion=['Prepa','Licenciatura','Egresado']
df_clase['Condicion de estudio']= np.select(condiciones,valor_condicion,default='Dato invalido')
df_clase

,Apellido,Edad,Estado,Edad en dias,Edad en meses,Mayor de edad,Condicion de estudio
Nombre,,,,,,,
Juan,Perez,23,Nuevo Leon,8395,276,Es mayor de edad,Egresado
Raul,Gonzalez,17,Coahuila,6205,204,Menor de edad,Prepa
Jimena,Rosas,20,Nuevo Leon,7300,240,Es mayor de edad,Licenciatura
Alejandra,Saldaña,21,Verecruz,7665,252,Es mayor de edad,Licenciatura

In [86]:
#.count cuenta cuantos datos tenemos en cierta columna
df_clase['Edad'].count()

4

In [87]:
#ahora contaremos cuantos son mayores de edad y cuentos son menores de edad

df_clase.value_counts('Mayor de edad')

Mayor de edad
Es mayor de edad    3
Menor de edad       1
dtype: int64

In [93]:
#ahora contaremos cuantos son de cada grado de estudio

df_clase.value_counts('Condicion de estudio')

Condicion de estudio
Licenciatura    2
Egresado        1
Prepa           1
dtype: int64

In [98]:
#vamos a sacar los promedio de cada agrupacion que hicimos

#primero los acomodamos por la columna mayor de edad
df_clase.groupby('Mayor de edad').mean()

<ipython-input-98-d9bae1e38c4c>:4: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_clase.groupby('Mayor de edad').mean()

                       Edad  Edad en dias  Edad en meses
Mayor de edad
Es mayor de edad  21.333333   7786.666667          256.0
Menor de edad     17.000000   6205.000000          204.0

In [103]:
#ahora vamos a seleccionar solo una columna, que sera la de edad
df_clase.groupby('Mayor de edad').mean().round(1)['Edad']

<ipython-input-103-63c9d05c7bae>:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_clase.groupby('Mayor de edad').mean().round(1)['Edad']

Mayor de edad
Es mayor de edad    21.3
Menor de edad       17.0
Name: Edad, dtype: float64

In [109]:
#agg
#sirve para resumir

#ahora vamos a resumir cuantos hay en cada columna
df_clase.agg(['count'])

,Apellido,Edad,Estado,Edad en dias,Edad en meses,Mayor de edad,Condicion de estudio
count,4,4,4,4,4,4,4

In [107]:
#ahora vamos a resumir cuantos hay en cada columna con la media
df_clase.agg(['count','mean'])

<ipython-input-107-1f03afa34c2f>:2: FutureWarning: ['Apellido', 'Estado', 'Mayor de edad', 'Condicion de estudio'] did not aggregate successfully. If any error is raised this will raise in a future version of pandas. Drop these columns/ops to avoid this warning.
  df_clase.agg(['count','mean'])

,Apellido,Edad,Estado,Edad en dias,Edad en meses,Mayor de edad,Condicion de estudio
count,4.0,4.00,4.0,4.00,4.0,4.0,4.0
mean,NaN,20.25,NaN,7391.25,243.0,NaN,NaN

In [ ]:
#ahora query

In [110]:
#selaccionar a alejandra
df_clase.query('Nombre=="Alejandra"')

,Apellido,Edad,Estado,Edad en dias,Edad en meses,Mayor de edad,Condicion de estudio
Nombre,,,,,,,
Alejandra,Saldaña,21,Verecruz,7665,252,Es mayor de edad,Licenciatura

In [118]:
#seleccionar a alejandra y que sea mayor a 20
df_clase.query('Nombre=="Alejandra"'&'Edad>20')

TypeError: ignored

In [128]:
calificaciones=pd.read_csv('https://raw.githubusercontent.com/jimmyzac/Estadistica-Aplicada-FCFM-UANL/main/bases_datos/Calificaciones.csv')
calificaciones

    Id            Nombre   Apellido  Calficación Final
0    1           ANTONIO     GARCIA                 73
1    2            MANUEL  FERNANDEZ                 19
2    3              JOSE   GONZALEZ                 38
3    4             DAVID      PEREZ                 14
4    5              JUAN      LOPEZ                 99
5    6      JOSE ANTONIO  RODRIGUEZ                 66
6    7            JAVIER    SANCHEZ                 46
7    8         JOSE LUIS      GOMEZ                 89
8    9  FRANCISCO JAVIER    JIMENEZ                 10
9   10            CARLOS       RUIZ                 62
10  11             JESUS     ALONSO                 94
11  12         ALEJANDRO  HERNANDEZ                 17
12  13            MIGUEL       DIAZ                 85
13  14       JOSE MANUEL  GUTIERREZ                 34
14  15            RAFAEL    ALVAREZ                 86
15  16      MIGUEL ANGEL     MORENO                100
16  17             PEDRO      MUÑOZ                  1
17  18             PABLO     BLANCO                 64
18  19             ANGEL        GIL                100
19  20            SERGIO    AGUIRRE                  2
20  21        JOSE MARIA       DIEZ                 29
21  22          FERNANDO    SALAZAR                 51
22  23             JORGE      RAMOS                 76
23  24              LUIS  DOMINGUEZ                 12
24  25           ALBERTO      ORTIZ                 99
25  26       JUAN CARLOS     IBAÑEZ                 43
26  27            ALVARO    RAMIREZ                 40
27  28            ADRIAN       SAEZ                  7

In [123]:
#da la informacion de los datos
calificaciones.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28 entries, 0 to 27
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Id                 28 non-null     int64
 1   Nombre             28 non-null     object
 2   Apellido           28 non-null     object
 3   Calficación Final  28 non-null     int64
dtypes: int64(2), object(2)
memory usage: 1.0+ KB

In [124]:
#da las estadisticas descriptivas de los datos
calificaciones.describe()

              Id  Calficación Final
count  28.000000          28.000000
mean   14.500000          52.000000
std     8.225975          34.113102
min     1.000000           1.000000
25%     7.750000          18.500000
50%    14.500000          48.500000
75%    21.250000          85.250000
max    28.000000         100.000000

In [125]:
#da el tamaño de los datos, primero filas y luego columnas
calificaciones.shape

(28, 4)

In [129]:
#te muestra las primeras califiaciones que quieras
calificaciones.head(5)

   Id   Nombre   Apellido  Calficación Final
0   1  ANTONIO     GARCIA                 73
1   2   MANUEL  FERNANDEZ                 19
2   3     JOSE   GONZALEZ                 38
3   4    DAVID      PEREZ                 14
4   5     JUAN      LOPEZ                 99

In [130]:
#te muestra las ultimas observaciones que quieras
calificaciones.tail(5)

    Id       Nombre   Apellido  Calficación Final
23  24         LUIS  DOMINGUEZ                 12
24  25      ALBERTO      ORTIZ                 99
25  26  JUAN CARLOS     IBAÑEZ                 43
26  27       ALVARO    RAMIREZ                 40
27  28       ADRIAN       SAEZ                  7

In [153]:
from sqlalchemy import column
##vamos a elegir todas las columnas menos id, es decir vamos a eliminar la columna id

# usamos iloc, seleccionamos todas las filas y accedemos a las columnas diciendole que se quede con todas menos con id
cal=calificaciones.loc[:,calificaciones.columns!='Id']
cal.head(5)

    Nombre   Apellido  Calficación Final
0  ANTONIO     GARCIA                 73
1   MANUEL  FERNANDEZ                 19
2     JOSE   GONZALEZ                 38
3    DAVID      PEREZ                 14
4     JUAN      LOPEZ                 99

In [166]:
#vamos a renombrar la columna calificacion final ya que esta mal escrito
cal=calificaciones.rename(columns={'Calficación Final':'Cal Final'})
cal.head(5)

    Nombre   Apellido  Cal Final
0  ANTONIO     GARCIA         73
1   MANUEL  FERNANDEZ         19
2     JOSE   GONZALEZ         38
3    DAVID      PEREZ         14
4     JUAN      LOPEZ         99

In [167]:
cal['Estatus']=np.where(cal['Cal Final']>=70,'Aprobado','Reprobado')

In [168]:
cal.head()

    Nombre   Apellido  Cal Final    Estatus
0  ANTONIO     GARCIA         73   Aprobado
1   MANUEL  FERNANDEZ         19  Reprobado
2     JOSE   GONZALEZ         38  Reprobado
3    DAVID      PEREZ         14  Reprobado
4     JUAN      LOPEZ         99   Aprobado